/* Generated by gbrecomp from toshinden */
#include "toshinden_internal.h"
#include "gbrt.h"
#include <stdio.h>
#include <stdlib.h>

/* Bank dispatch - routes calls to the correct bank function */
void toshinden_dispatch_00(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_01(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_02(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_03(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_04(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_05(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_06(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_07(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_08(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_09(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_0a(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_0b(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_0c(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_0d(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_0e(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_0f(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_10(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_11(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_12(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_13(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_14(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_15(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_16(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_17(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_18(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_19(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_1a(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_1b(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_1c(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_1d(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_1e(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_1f(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_20(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_21(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_22(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_23(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_24(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_25(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_26(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_27(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_28(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_29(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_2a(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_2b(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_2c(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_2d(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_2e(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_2f(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_30(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_31(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_32(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_33(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_34(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_35(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_36(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_37(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_38(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_39(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_3a(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_3b(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_3c(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_3d(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_3e(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_3f(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_40(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_41(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_42(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_43(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_44(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_45(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_46(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_47(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_48(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_49(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_4a(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_4b(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_4c(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_4d(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_4e(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_4f(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_50(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_51(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_52(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_53(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_54(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_55(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_56(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_57(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_58(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_59(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_5a(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_5b(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_5c(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_5d(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_5e(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_5f(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_60(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_61(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_62(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_63(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_64(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_65(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_66(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_67(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_68(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_69(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_6a(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_6b(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_6c(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_6d(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_6e(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_6f(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_70(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_71(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_72(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_73(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_74(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_75(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_76(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_77(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_78(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_79(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_7a(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_7b(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_7c(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_7d(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_7e(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_7f(GBContext* ctx, uint16_t addr, uint16_t bank);
void toshinden_dispatch_ff(GBContext* ctx, uint16_t addr, uint16_t bank);

static uint8_t ram_overlay_0_matches(GBContext* ctx) {
    if (gb_read8(ctx, 0xff80) != 0xe0) return 0;
    if (gb_read8(ctx, 0xff81) != 0x46) return 0;
    if (gb_read8(ctx, 0xff82) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff83) != 0x28) return 0;
    if (gb_read8(ctx, 0xff84) != 0x3d) return 0;
    if (gb_read8(ctx, 0xff85) != 0x20) return 0;
    if (gb_read8(ctx, 0xff86) != 0xfd) return 0;
    if (gb_read8(ctx, 0xff87) != 0xc9) return 0;
    return 1;
}

static uint8_t try_dispatch_compiled_ram_overlay(GBContext* ctx, uint16_t addr, uint16_t bank) {
    if (addr >= 0xff80 && addr < 0xff88) {
        if (!ram_overlay_0_matches(ctx)) {
            return 0;
        }
        switch (addr) {
            case 0xff80:
                toshinden_dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff81:
                toshinden_dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff82:
                toshinden_dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff83:
                toshinden_dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff84:
                toshinden_dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff85:
                toshinden_dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff87:
                toshinden_dispatch_ff(ctx, addr, bank);
                return 1;
            default:
                return 0;
        }
    }
    return 0;
}

void gb_dispatch(GBContext* ctx, uint16_t addr) {
    ctx->pc = addr;
    while (!ctx->stopped && !ctx->halted) {
        gbrt_note_generated_indirect_dispatch(ctx);
        addr = ctx->pc;
        uint16_t bank = gb_resolve_rom_bank(ctx, addr);
        if (gbrt_instruction_limit > 0) {
            if (gbrt_instruction_count >= gbrt_instruction_limit) {
                fprintf(stderr, "[LIMIT] Reached instruction limit %llu\n", (unsigned long long)gbrt_instruction_limit);
                exit(0);
            }
            gbrt_instruction_count++;
        }
        if (ctx->trace_entries_enabled) gbrt_log_trace(ctx, bank, addr);
        if (gbrt_trace_enabled) {
            fprintf(stderr, "[TRACE] Dispatch 0x%04X (Bank %d)\n", addr, bank);
        }
        if (gbrt_try_execute_hram_stub(ctx, addr)) {
            if (ctx->single_step_mode) break;
            continue;
        }
        if (gbrt_try_execute_highmem_stub(ctx, addr)) {
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        if (gbrt_try_execute_ram_stub(ctx, addr)) {
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        if (try_dispatch_compiled_ram_overlay(ctx, addr, bank)) {
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        if (addr >= 0xFF80 && addr <= 0xFFFE) {
            gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_WRITABLE_HRAM, 0);
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        switch (addr >> 8) {
            case 0x00: toshinden_dispatch_00(ctx, addr, bank); break;
            case 0x01: toshinden_dispatch_01(ctx, addr, bank); break;
            case 0x02: toshinden_dispatch_02(ctx, addr, bank); break;
            case 0x03: toshinden_dispatch_03(ctx, addr, bank); break;
            case 0x04: toshinden_dispatch_04(ctx, addr, bank); break;
            case 0x05: toshinden_dispatch_05(ctx, addr, bank); break;
            case 0x06: toshinden_dispatch_06(ctx, addr, bank); break;
            case 0x07: toshinden_dispatch_07(ctx, addr, bank); break;
            case 0x08: toshinden_dispatch_08(ctx, addr, bank); break;
            case 0x09: toshinden_dispatch_09(ctx, addr, bank); break;
            case 0x0a: toshinden_dispatch_0a(ctx, addr, bank); break;
            case 0x0b: toshinden_dispatch_0b(ctx, addr, bank); break;
            case 0x0c: toshinden_dispatch_0c(ctx, addr, bank); break;
            case 0x0d: toshinden_dispatch_0d(ctx, addr, bank); break;
            case 0x0e: toshinden_dispatch_0e(ctx, addr, bank); break;
            case 0x0f: toshinden_dispatch_0f(ctx, addr, bank); break;
            case 0x10: toshinden_dispatch_10(ctx, addr, bank); break;
            case 0x11: toshinden_dispatch_11(ctx, addr, bank); break;
            case 0x12: toshinden_dispatch_12(ctx, addr, bank); break;
            case 0x13: toshinden_dispatch_13(ctx, addr, bank); break;
            case 0x14: toshinden_dispatch_14(ctx, addr, bank); break;
            case 0x15: toshinden_dispatch_15(ctx, addr, bank); break;
            case 0x16: toshinden_dispatch_16(ctx, addr, bank); break;
            case 0x17: toshinden_dispatch_17(ctx, addr, bank); break;
            case 0x18: toshinden_dispatch_18(ctx, addr, bank); break;
            case 0x19: toshinden_dispatch_19(ctx, addr, bank); break;
            case 0x1a: toshinden_dispatch_1a(ctx, addr, bank); break;
            case 0x1b: toshinden_dispatch_1b(ctx, addr, bank); break;
            case 0x1c: toshinden_dispatch_1c(ctx, addr, bank); break;
            case 0x1d: toshinden_dispatch_1d(ctx, addr, bank); break;
            case 0x1e: toshinden_dispatch_1e(ctx, addr, bank); break;
            case 0x1f: toshinden_dispatch_1f(ctx, addr, bank); break;
            case 0x20: toshinden_dispatch_20(ctx, addr, bank); break;
            case 0x21: toshinden_dispatch_21(ctx, addr, bank); break;
            case 0x22: toshinden_dispatch_22(ctx, addr, bank); break;
            case 0x23: toshinden_dispatch_23(ctx, addr, bank); break;
            case 0x24: toshinden_dispatch_24(ctx, addr, bank); break;
            case 0x25: toshinden_dispatch_25(ctx, addr, bank); break;
            case 0x26: toshinden_dispatch_26(ctx, addr, bank); break;
            case 0x27: toshinden_dispatch_27(ctx, addr, bank); break;
            case 0x28: toshinden_dispatch_28(ctx, addr, bank); break;
            case 0x29: toshinden_dispatch_29(ctx, addr, bank); break;
            case 0x2a: toshinden_dispatch_2a(ctx, addr, bank); break;
            case 0x2b: toshinden_dispatch_2b(ctx, addr, bank); break;
            case 0x2c: toshinden_dispatch_2c(ctx, addr, bank); break;
            case 0x2d: toshinden_dispatch_2d(ctx, addr, bank); break;
            case 0x2e: toshinden_dispatch_2e(ctx, addr, bank); break;
            case 0x2f: toshinden_dispatch_2f(ctx, addr, bank); break;
            case 0x30: toshinden_dispatch_30(ctx, addr, bank); break;
            case 0x31: toshinden_dispatch_31(ctx, addr, bank); break;
            case 0x32: toshinden_dispatch_32(ctx, addr, bank); break;
            case 0x33: toshinden_dispatch_33(ctx, addr, bank); break;
            case 0x34: toshinden_dispatch_34(ctx, addr, bank); break;
            case 0x35: toshinden_dispatch_35(ctx, addr, bank); break;
            case 0x36: toshinden_dispatch_36(ctx, addr, bank); break;
            case 0x37: toshinden_dispatch_37(ctx, addr, bank); break;
            case 0x38: toshinden_dispatch_38(ctx, addr, bank); break;
            case 0x39: toshinden_dispatch_39(ctx, addr, bank); break;
            case 0x3a: toshinden_dispatch_3a(ctx, addr, bank); break;
            case 0x3b: toshinden_dispatch_3b(ctx, addr, bank); break;
            case 0x3c: toshinden_dispatch_3c(ctx, addr, bank); break;
            case 0x3d: toshinden_dispatch_3d(ctx, addr, bank); break;
            case 0x3e: toshinden_dispatch_3e(ctx, addr, bank); break;
            case 0x3f: toshinden_dispatch_3f(ctx, addr, bank); break;
            case 0x40: toshinden_dispatch_40(ctx, addr, bank); break;
            case 0x41: toshinden_dispatch_41(ctx, addr, bank); break;
            case 0x42: toshinden_dispatch_42(ctx, addr, bank); break;
            case 0x43: toshinden_dispatch_43(ctx, addr, bank); break;
            case 0x44: toshinden_dispatch_44(ctx, addr, bank); break;
            case 0x45: toshinden_dispatch_45(ctx, addr, bank); break;
            case 0x46: toshinden_dispatch_46(ctx, addr, bank); break;
            case 0x47: toshinden_dispatch_47(ctx, addr, bank); break;
            case 0x48: toshinden_dispatch_48(ctx, addr, bank); break;
            case 0x49: toshinden_dispatch_49(ctx, addr, bank); break;
            case 0x4a: toshinden_dispatch_4a(ctx, addr, bank); break;
            case 0x4b: toshinden_dispatch_4b(ctx, addr, bank); break;
            case 0x4c: toshinden_dispatch_4c(ctx, addr, bank); break;
            case 0x4d: toshinden_dispatch_4d(ctx, addr, bank); break;
            case 0x4e: toshinden_dispatch_4e(ctx, addr, bank); break;
            case 0x4f: toshinden_dispatch_4f(ctx, addr, bank); break;
            case 0x50: toshinden_dispatch_50(ctx, addr, bank); break;
            case 0x51: toshinden_dispatch_51(ctx, addr, bank); break;
            case 0x52: toshinden_dispatch_52(ctx, addr, bank); break;
            case 0x53: toshinden_dispatch_53(ctx, addr, bank); break;
            case 0x54: toshinden_dispatch_54(ctx, addr, bank); break;
            case 0x55: toshinden_dispatch_55(ctx, addr, bank); break;
            case 0x56: toshinden_dispatch_56(ctx, addr, bank); break;
            case 0x57: toshinden_dispatch_57(ctx, addr, bank); break;
            case 0x58: toshinden_dispatch_58(ctx, addr, bank); break;
            case 0x59: toshinden_dispatch_59(ctx, addr, bank); break;
            case 0x5a: toshinden_dispatch_5a(ctx, addr, bank); break;
            case 0x5b: toshinden_dispatch_5b(ctx, addr, bank); break;
            case 0x5c: toshinden_dispatch_5c(ctx, addr, bank); break;
            case 0x5d: toshinden_dispatch_5d(ctx, addr, bank); break;
            case 0x5e: toshinden_dispatch_5e(ctx, addr, bank); break;
            case 0x5f: toshinden_dispatch_5f(ctx, addr, bank); break;
            case 0x60: toshinden_dispatch_60(ctx, addr, bank); break;
            case 0x61: toshinden_dispatch_61(ctx, addr, bank); break;
            case 0x62: toshinden_dispatch_62(ctx, addr, bank); break;
            case 0x63: toshinden_dispatch_63(ctx, addr, bank); break;
            case 0x64: toshinden_dispatch_64(ctx, addr, bank); break;
            case 0x65: toshinden_dispatch_65(ctx, addr, bank); break;
            case 0x66: toshinden_dispatch_66(ctx, addr, bank); break;
            case 0x67: toshinden_dispatch_67(ctx, addr, bank); break;
            case 0x68: toshinden_dispatch_68(ctx, addr, bank); break;
            case 0x69: toshinden_dispatch_69(ctx, addr, bank); break;
            case 0x6a: toshinden_dispatch_6a(ctx, addr, bank); break;
            case 0x6b: toshinden_dispatch_6b(ctx, addr, bank); break;
            case 0x6c: toshinden_dispatch_6c(ctx, addr, bank); break;
            case 0x6d: toshinden_dispatch_6d(ctx, addr, bank); break;
            case 0x6e: toshinden_dispatch_6e(ctx, addr, bank); break;
            case 0x6f: toshinden_dispatch_6f(ctx, addr, bank); break;
            case 0x70: toshinden_dispatch_70(ctx, addr, bank); break;
            case 0x71: toshinden_dispatch_71(ctx, addr, bank); break;
            case 0x72: toshinden_dispatch_72(ctx, addr, bank); break;
            case 0x73: toshinden_dispatch_73(ctx, addr, bank); break;
            case 0x74: toshinden_dispatch_74(ctx, addr, bank); break;
            case 0x75: toshinden_dispatch_75(ctx, addr, bank); break;
            case 0x76: toshinden_dispatch_76(ctx, addr, bank); break;
            case 0x77: toshinden_dispatch_77(ctx, addr, bank); break;
            case 0x78: toshinden_dispatch_78(ctx, addr, bank); break;
            case 0x79: toshinden_dispatch_79(ctx, addr, bank); break;
            case 0x7a: toshinden_dispatch_7a(ctx, addr, bank); break;
            case 0x7b: toshinden_dispatch_7b(ctx, addr, bank); break;
            case 0x7c: toshinden_dispatch_7c(ctx, addr, bank); break;
            case 0x7d: toshinden_dispatch_7d(ctx, addr, bank); break;
            case 0x7e: toshinden_dispatch_7e(ctx, addr, bank); break;
            case 0x7f: toshinden_dispatch_7f(ctx, addr, bank); break;
            case 0xff: toshinden_dispatch_ff(ctx, addr, bank); break;
            default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_PAGE_NOT_COMPILED, 0); break;
        }
        if (ctx->single_step_mode) break;
    }
}

void gb_dispatch_call(GBContext* ctx, uint16_t addr) {
    gb_dispatch(ctx, addr);
}

const GBConfig* toshinden_default_config(void) {
    static const GBConfig config = {
        .model = GB_MODEL_DMG,
        .cgb_compatibility_mode = false,
        .cartridge_supports_cgb = false,
        .cartridge_requires_cgb = false,
        .enable_bootrom = false,
        .enable_audio = true,
        .enable_serial = true,
        .speed_percent = 100,
        .native_presentation_enabled = false,
    };
    return &config;
}

void toshinden_init(GBContext* ctx, const uint8_t* rom_data, size_t rom_size) {
    gb_context_load_rom(ctx, rom_data, rom_size);
    gb_context_reset(ctx, true);
}

void toshinden_run(GBContext* ctx) {
    // Start the trampoline loop - execution will stay here until stopped
    gb_dispatch(ctx, ctx->pc);
}
