/* Generated by gbrecomp */
#ifndef toshinden_H
#define toshinden_H

#include "gbrt.h"

const GBConfig* toshinden_default_config(void);
void toshinden_run(GBContext* ctx);
void toshinden_init(GBContext* ctx, const uint8_t* rom_data, size_t rom_size);
int toshinden_main(int argc, char* argv[]);

#endif
